### ISSUE TITLE
Include branch name in PR title

### ISSUE THREAD

**Issue by superseb** [rancherlabs/updatecli-automation#4]
To better differentiate created PRs, it would be nice to include the branch name in the PR title. We have some PRs that use `[<branch_name>] Title` but another example is Renovate which uses `Title (<branch_name>)`.

<img width="472" alt="pr-branch-name" src="https://user-images.githubusercontent.com/2620179/204264204-90388c91-468a-4ec9-b9db-559fa4917e1a.png">

**Comment by macedogm** [comment]
We can do that by customizing the `title` in `pullrequests`:

 https://github.com/rancherlabs/updatecli-automation/blob/34a0cc4687c8c069feaed457cf843c6cbd6a8507/updatecli/updatecli.d/rancher/rancher/v2.7/kustomize.yaml#L17

For example:
```yaml
title: "[release/v2.7] Bump Kustomize version"
```

We can turn the branch into a variable, because we are also using it in:

https://github.com/rancherlabs/updatecli-automation/blob/34a0cc4687c8c069feaed457cf843c6cbd6a8507/updatecli/updatecli.d/rancher/rancher/v2.7/kustomize.yaml#L13
